version: '3'

services:
  nikhil-springboot-container:
    image: nikhil-spring-boot-docker-compose:${version}
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/nikhil-springboot-container
    ports:
      - "8080-8100:8080"
