apiVersion: apps/v1
kind: Deployment
metadata:
  name: nikhil-springboot
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nikhil-springboot
  template:
    metadata:
      labels:
        app: nikhil-springboot
    spec:
      containers:
        - name: springboot
          image: nikhilsharma6311/nikhil-docker-demo:${BUILD_NUMBER}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: nikhil-springboot
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: nikhil-springboot
